MVC-proj/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_proj.DAL;
using MVC_proj.Models;
using MVC_proj.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_proj.Controllers
{
    public class HomeController : Controller
    {
        private AppDbContext _context;

        public HomeController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(new HomeIndexViewModel
            {
                Products = _context.Products.Include(p => p.Category).ToList(),
                Categories = _context.Categories.FirstOrDefault(),
                Blogs = _context.Blogs.ToList(),
                Says = _context.Says.ToList(),
                Carousels = _context.Carousels.ToList()
            });
        }

        public async Task<IActionResult> Search(string searchedStr)
        {
            List<Carousel> carousels = _context.Carousels.ToList();

            if(string.IsNullOrWhiteSpace(searchedStr))
            {
                return PartialView("_CarouselSearchPartial", new List<Carousel>());
            }

            carousels = await _context.Carousels.Where(p => p.ImageName.ToLower().Contains(searchedStr.ToLower())).ToListAsync();
            return PartialView("_CarouselSearchPartial", carousels);
        }
    }
}

MVC-proj/ViewComponents/BlogViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MVC_proj.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_proj.ViewComponents
{
    public class BlogViewComponent : ViewComponent
    {
        private AppDbContext _context;

        public BlogViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke()
        {
            return View(_context.Blogs.ToList());
        }
    }
}

MVC-proj/ViewComponents/ProductViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_proj.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_proj.ViewComponents
{
    public class ProductViewComponent : ViewComponent
    {
        private AppDbContext _context;

        public ProductViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke()
        {
            var products = _context.Products.Include(p => p.Category).ToList();
            return View(products);
        }
    }
}

MVC-proj/ViewComponents/SayViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MVC_proj.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_proj.ViewComponents
{
    public class SayViewComponent : ViewComponent
    {
        private AppDbContext _context;

        public SayViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke()
        {
            return View(_context.Says.ToList());
        }
    }
}

MVC-proj/Views/Home/Index.cshtml
@model MVC_proj.ViewModels.HomeIndexViewModel
@{
    ViewData["Title"] = "Index";
}

<main>

    <!-- SLIDER START -->

    <section id="slider">
        <div class="owl-carousel slider">
            <div> <img src="~/img/h3-slider-background.jpg" alt=""> </div>
            <div> <img src="~/img/h3-slider-background-2.jpg" alt=""> </div>
            <div> <img src="~/img/h3-slider-background-3.jpg" alt=""> </div>
        </div>
        <div class="container context pl-lg-5 ml-lg-3">
            <div class="row">
                <div class="col-lg-5">
                    <div class="text">
                        <h1>Send <span>flowers</span> like</h1>
                        <h1>you mean it</h1>
                        <p class="text-black-50 d-none d-sm-block">
                            Where flowers are our inspiration to create lasting memories. Whatever the occasion, our flowers will
                            make it special cursus a sit amet mauris.
                        </p>
                    </div>
                    <div class="img">
                        <img src="~/img/h2-sign-img.png" alt="">
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- SLIDER END -->
    <!-- PRODUCTS START -->

    <section id="products">
        <div class="container">
            <div class="row pt-5">
                <div class="col-12 d-flex justify-content-between">
                    <ul class="category-mobile d-md-none list-unstyled">
                        <li>
                            <a href="" class="categories mr-2">Categories</a>
                            <i class="fas fa-caret-down"></i>
                            <ul class="category list-unstyled" style="display: none;">
                                <li><a href="" data-id="all">All</a></li>
                                <li><a href="" data-id="popular">Popular</a></li>
                                <li><a href="" data-id="winter">Winter</a></li>
                                <li><a href="" data-id="various">Various</a></li>
                                <li><a href="" data-id="exotic">Exotic</a></li>
                                <li><a href="" data-id="green">Greens</a></li>
                                <li><a href="" data-id="cactuse">Cactuses</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="category d-none d-md-flex list-unstyled">
                        <li><a href="" data-id="all">All</a></li>
                        <li><a href="" data-id="popular">Popular</a></li>
                        <li><a href="" data-id="winter">Winter</a></li>
                        <li><a href="" data-id="various">Various</a></li>
                        <li><a href="" data-id="exotic">Exotic</a></li>
                        <li><a href="" data-id="green">Greens</a></li>
                        <li><a href="" data-id="cactuse">Cactuses</a></li>
                    </ul>
                    <ul class="list-unstyled">
                        <li>
                            <a href="" class="mr-2">Filter</a>
                            <i class="fas fa-caret-down"></i>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row">
                @await Component.InvokeAsync("Product");
            </div>
            <div class="justify-content-center d-flex">
                <a id="loadmorebtn" class="btn btn-primary" asp-controller="Product">View All Products</a>
            </div>
        </div>
    </section>

    <!-- PRODUCTS END -->
    <!-- ABOUT START -->

    <section id="about">
        <div class="container py-5">
            <div class="row py-5">
                <div class="col-lg-6">
                    <div class="img">
                        <img src="~/img/h3-video-img.jpg" class="img-fluid" alt="">
                        <div class="player position-absolute rounded-circle d-flex align-items-center justify-content-center">
                            <i class="fas fa-play fa-lg"></i>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="about-text mt-5 mt-lg-0 px-lg-5">
                        <h1>Suprise Your <span>Valentine!</span> Let us arrange a smile.</h1>
                        <p class="py-3">
                            Where flowers are our inspiration to create lasting memories. Whatever the
                            occasion...
                        </p>
                        <ul class="list-unstyled">
                            <li class="mt-3">
                                <img src="~/img/h1-custom-icon.png" class="mr-2" alt=""> Hand picked just
                                for you.
                            </li>
                            <li class="mt-3">
                                <img src="~/img/h1-custom-icon.png" class="mr-2" alt=""> Unique flower
                                arrangements
                            </li>
                            <li class="mt-3">
                                <img src="~/img/h1-custom-icon.png" class="mr-2" alt=""> Best way to say
                                you care.
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- ABOUT END -->
    <!-- EXPERTS START -->

    <section id="experts">
        <div class="container">
            <div class="row py-5">
                <div class="offset-lg-3 col-lg-6">
                    <div class="section-title">
                        <h1>Flower Experts</h1>
                        <p class="text-black-50">
                            A perfect blend of creativity, energy, communication, happiness and
                            love. Let us arrange
                            a smile for you.
                        </p>
                    </div>
                </div>
            </div>
            <div class="row pb-5">
                <div class="col-md-6 col-lg-3">
                    <div class="item text-center">
                        <div class="img">
                            <img src="~/img/h3-team-img-1.png" class="img-fluid rounded-circle" alt="">
                        </div>
                        <div class="text mt-3">
                            <h6>CRYSTAL BROOKS</h6>
                            <p class="text-black-50">Florist</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="item text-center">
                        <div class="img">
                            <img src="~/img/h3-team-img-2.png" class="img-fluid rounded-circle" alt="">
                        </div>
                        <div class="text mt-3">
                            <h6>SHIRLEY HARRIS</h6>
                            <p class="text-black-50">Manager</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="item text-center">
                        <div class="img">
                            <img src="~/img/h3-team-img-3.png" class="img-fluid rounded-circle" alt="">
                        </div>
                        <div class="text mt-3">
                            <h6>BEVERLY CLARK</h6>
                            <p class="text-black-50">Florist</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="item text-center">
                        <div class="img">
                            <img src="~/img/h3-team-img-4.png" class="img-fluid rounded-circle" alt="">
                        </div>
                        <div class="text mt-3">
                            <h6>AMANDA WATKINS</h6>
                            <p class="text-black-50">Florist</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3"></div>
                <div class="col-lg-3"></div>
                <div class="col-lg-3"></div>
            </div>
        </div>
    </section>

    <!-- EXPERTS END -->
    <!-- SUBSCRIBE START -->

    <section id="subscribe">
        <div class="container py-5">
            <div class="row py-5">
                <div class="col-12">
                    <div class="content text-center py-5">
                        <h3>Join The Colorful Bunch!</h3>
                        <div class="form-group d-flex justify-content-center flex-wrap mt-5">
                            <input type="email" placeholder="Email Address" class="form-control-lg rounded-0">
                            <button class="btn btn-danger btn-lg rounded-0 px-5 mt-3 mt-sm-0">Subscribe</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- SUBSCRIBE END -->
    <!-- BLOG START -->

    <section id="blog">
        <div class="container">
            <div class="row py-5">
                <div class="offset-lg-3 col-lg-6">
                    <div class="section-title">
                        <h1>From our Blog</h1>
                        <p class="text-black-50">
                            A perfect blend of creativity, energy, communication, happiness and
                            love. Let us arrange
                            a smile for you.
                        </p>
                    </div>
                </div>
            </div>
            <div class="row pb-5">
                @await Component.InvokeAsync("Blog"); 
            </div>
        </div>
    </section>

    <!-- BLOG END -->
    <!-- SAY START -->

    <section id="say">
        <div class="container">
            <div class="row py-5 justify-content-center">
                <div class="col-md-8 col-xl-6">
                    <div class="owl-carousel say">
                        @await Component.InvokeAsync("Say") 
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- SAY END -->
    <!-- INSTAGRAM START -->

    <section id="instagram">
        <div class="owl-carousel instagram">
            @foreach (var item in Model.Carousels)
            {
            <div><img src="~/img/@item.ImageName" class="img-fluid" alt=""></div>
            }
        </div>
        <div class="hastag bg-light text-muted py-2 px-3">
            #FIORELLO
        </div>
    </section>

    <!-- INSTAGRAM END -->

</main>