MVC-proj/Models/Layout.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_proj.Models
{
    public class Layout
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(70)]
        public string LinkedinUrl { get; set; }
        [Column("linkedin")]
        public string LinkedinTitle { get; set; }
        public string FacebookUrl { get; set; }
        public string FacebookTitle { get; set; }
        [MaxLength(50)]
        public string Description { get; set; }
    }
}

MVC-proj/Areas/Admin/Controllers/LayoutController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_proj.DAL;
using MVC_proj.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_proj.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class LayoutController : Controller
    {

        private readonly AppDbContext _context;

        public LayoutController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var layouts = await _context.Layouts.ToListAsync();
            return View(layouts);
        }

        public async Task<IActionResult> Detail(int id)
        {
            var layout = await _context.Layouts.FindAsync(id);
            if(layout == null)
            {
                return NotFound();
            }

            return View(layout);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Layout layout)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }

            await _context.Layouts.AddAsync(layout);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

MVC-proj/Areas/Admin/Views/Layout/Create.cshtml
@model Layout
@{
    ViewData["Title"] = "Create";
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Create New Layout</h4>
                    <form class="forms-sample" method="post" asp-controller="Layout" asp-action="Create">
                        <div class="form-group">
                            <label asp-for="LinkedinUrl">Linkedin URL</label>
                            <input class="form-control" asp-for="LinkedinUrl" placeholder="Linkedin URL">
                            <span class="text-danger" asp-validation-for="LinkedinUrl"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="LinkedinTitle">Linkedin Title</label>
                            <input class="form-control" asp-for="LinkedinTitle" placeholder="Linkedin Title">
                            <span class="text-danger" asp-validation-for="LinkedinTitle"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="FacebookUrl">Facebook URL</label>
                            <input class="form-control" asp-for="FacebookUrl" placeholder="Facebook URL">
                            <span class="text-danger" asp-validation-for="FacebookUrl"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="FacebookTitle">Facebook Title</label>
                            <input class="form-control" asp-for="FacebookTitle" placeholder="Facebook Title">
                            <span class="text-danger" asp-validation-for="FacebookTitle"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description">Description</label>
                            <input class="form-control" asp-for="Description" placeholder="Facebook Title">
                            <span class="text-danger" asp-validation-for="Description"></span>
                        </div>
                        <button type="submit" class="btn btn-primary me-2">Submit</button>
                        <button class="btn btn-light">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

MVC-proj/Areas/Admin/Views/Layout/Detail.cshtml
@model Layout
@{
    ViewData["Title"] = "Detail";
}

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Details:</h4>
                <p class="card-description">

                </p>
                <p> 
                    @Model.Description pages
                </p>
            </div>
        </div>
    </div>
</div>

MVC-proj/Areas/Admin/Views/Layout/Index.cshtml
@model List<Layout>
@{
    ViewData["Title"] = "Index";
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Basic Table</h4>
                    <p class="card-description">
                        Add class <code>.table</code>
                    </p>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Facebook</th>
                                    <th>Facebook URL</th>
                                    <th>LinkedIn</th>
                                    <th>LinkedIn URL</th>
                                    <th>Operations</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.LinkedinTitle</td>
                                        <td>@item.LinkedinUrl</td>
                                        <td>@item.FacebookTitle</td>
                                        <td>@item.FacebookUrl</td>
                                        <td>
                                            <a class="btn btn-primary" asp-controller="Layout" asp-action="Detail" asp-route-id="@item.Id">Detail</a>
                                            <a class="btn btn-warning">Update</a>
                                            <a class="btn btn-danger">Delete</a>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>